"""Langfuse tracing (Langfuse Python SDK v4, OpenTelemetry-based) — down to every step.

1 trace = 1 /invocations request. Standard observation tree (fixed names for filters/dashboards):

  agent.invoke  [agent]   input=message · output=answer · user_id · session_id · tags · version
  ├─ auth                  [event]  output={user_id, mode, iss, aud, exp}   (token is NOT logged)
  ├─ tools.collect         [span]   output={local, memory, mcp:{server:[tools]}, mcp_errors}
  │   └─ mcp.list_tools    [span]   input={server, transport, auth, cached} · output=[tool names]
  └─ agent.graph           [chain]  (LangGraph — auto-generated by CallbackHandler, input/output = state)
      ├─ compress          [chain]
      │   └─ context.compress [span] metadata={tokens_before, threshold, decision, removed}
      │       └─ context.summarize [generation] model · usage · cost
      ├─ recall            [chain]
      │   └─ memory.recall [span]  input={query, namespace, limit} · output={facts, count, latency}
      ├─ agent             [chain]  (linked to the Langfuse prompt version when using Prompt Management)
      │   ├─ context.hard_trim [event, WARNING] when a hard cut is needed
      │   └─ ChatOpenAI    [generation] input=messages+tool schemas · output · model ·
      │                    model_parameters · usage{input, output, input_cache_read,
      │                    cache_creation_*, output_reasoning} · cost · TTFT (completion_start_time)
      ├─ tools             [chain]
      │   └─ <tool>        [tool]   input=args · output=result · level=ERROR on failure
      │       └─ memory.save [span] (when tool = remember)
      └─ agent ... (loop)
  score user_feedback (-1|0|1) attached to trace_id when the frontend sends feedback.

Env (read by the SDK): LANGFUSE_PUBLIC_KEY, LANGFUSE_SECRET_KEY, LANGFUSE_BASE_URL (or LANGFUSE_HOST),
LANGFUSE_SAMPLE_RATE, LANGFUSE_TRACING_ENABLED, LANGFUSE_DEBUG. Missing keys => every function is a no-op.
"""

from __future__ import annotations

import contextlib
import hashlib
import logging
import re
import time
from collections.abc import Iterator
from typing import Any

from app.config import Settings

log = logging.getLogger(__name__)

_client: Any = None
# Secret KEYS: the key name (normalized: lower, "-"/" " → "_") is split on "_"; it is secret if a part is one of
# _SECRET_PARTS or it contains one of _SECRET_SUBSTRINGS. Matches x_api_key, refresh_token, id_token, set_cookie,
# langfuse_secret_key, x_greennode_agentbase_custom_api_key… but NOT max_tokens / prompt_tokens (usage numbers).
_SECRET_PARTS = {
    "authorization",
    "token",
    "secret",
    "password",
    "passwd",
    "cookie",
    "credential",
    "credentials",
}
_SECRET_SUBSTRINGS = ("api_key", "apikey", "private_key", "secret_key", "access_key")
_NOT_SECRET_LAST_PARTS = {"usage", "type", "use", "count", "limit", "expires", "expiry", "ttl"}
# Credential after Bearer/Basic: ≥ 8 chars with a digit/token symbol or a lower→UPPER switch inside the word
# (base64 like "dXNlcjpw…") — so prose like "basic idea", "Basic plan", "Basic Information" is left alone.
_BEARER_RE = re.compile(  # case-insensitive keyword only: the lower→UPPER check below must stay case-sensitive
    r"\b((?i:bearer|basic))(\s+)(?=[A-Za-z0-9._~+/-]*(?:[0-9+/=._~-]|[a-z][A-Z]))[A-Za-z0-9\-._~+/]{8,}=*"
)
_JWT_RE = re.compile(r"eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}")
_API_KEY_RE = re.compile(r"\b(?:sk|vn|rk)-[A-Za-z0-9_-]{20,}")  # OpenAI-style / GreenNode MaaS keys
# Default PII (TRACE_MASK_PII): email, VN phone (+84/0 + 9 digits), card numbers (Luhn), CCCD 12 digits, and
# CMND 9 digits ONLY after an ID keyword (a bare 9-digit number is usually an amount). Extend per project.
_EMAIL_RE = re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")
_PHONE_RE = re.compile(r"(?<!\d)(?:\+?84|0)(?:[\s.-]?\d){9}(?!\d)")
_CARD_RE = re.compile(r"(?<!\d)\d(?:[ -]?\d){14,18}(?!\d)")
_CCCD_RE = re.compile(r"(?<!\d)\d{12}(?!\d)")
_CMND_RE = re.compile(r"(?i)\b(cmnd|cccd|cmt|chứng minh|căn cước|id)(\D{0,12})(?<!\d)\d{9}(?!\d)")
_mask_pii = True


# --------------------------------------------------------------------------- lifecycle
def init_tracing(settings: Settings) -> None:
    """Call once at startup (lifespan)."""
    global _client
    if not settings.langfuse_enabled:
        log.info("Langfuse disabled (missing LANGFUSE_PUBLIC_KEY/SECRET_KEY)")
        return
    from langfuse import Langfuse

    global _mask_pii
    _mask_pii = settings.trace_mask_pii
    _client = Langfuse(environment=settings.app_env, release=settings.agent_version, mask=_mask)
    log.info(
        "Langfuse tracing enabled (env=%s, release=%s)", settings.app_env, settings.agent_version
    )


def shutdown_tracing() -> None:
    if _client is not None:
        _client.flush()
        _client.shutdown()


def get_client() -> Any:
    return _client


def _is_secret_key(key: Any) -> bool:
    # camelCase → snake (accessToken → access_token), then "-"/" " → "_"
    k = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", str(key))
    k = re.sub(r"[-\s]+", "_", k.lower())
    parts = k.split("_")
    if parts[-1] in _NOT_SECRET_LAST_PARTS:  # token_usage, credential_type, token_use… are metadata
        return False
    return any(p in _SECRET_PARTS for p in parts) or any(x in k for x in _SECRET_SUBSTRINGS)


def _luhn_ok(digits: str) -> bool:
    total = 0
    for i, ch in enumerate(reversed(digits)):
        d = int(ch) * (2 if i % 2 else 1)
        total += d - 9 if d > 9 else d
    return total % 10 == 0


def _mask_card(m: re.Match) -> str:
    digits = re.sub(r"\D", "", m.group(0))
    # 15–19 digits (Amex 15, Visa/MC 16…): excludes 13-digit epoch-ms timestamps that happen to pass Luhn
    return "***CARD***" if 15 <= len(digits) <= 19 and _luhn_ok(digits) else m.group(0)


def _mask_text(text: str) -> str:
    out = _BEARER_RE.sub(r"\1\2***", text)
    out = _API_KEY_RE.sub("***KEY***", _JWT_RE.sub("***JWT***", out))
    if _mask_pii:
        out = _EMAIL_RE.sub("***EMAIL***", out)
        out = _CARD_RE.sub(_mask_card, out)  # before phone/ID: a card contains shorter digit runs
        out = _PHONE_RE.sub("***PHONE***", out)
        out = _CCCD_RE.sub("***ID***", out)
        out = _CMND_RE.sub(r"\1\2***ID***", out)
    return out


def _mask(*, data: Any, **_: Any) -> Any:
    """Mask secrets (always) and PII (TRACE_MASK_PII) before anything leaves the process."""
    if isinstance(data, dict):
        return {k: ("***" if _is_secret_key(k) else _mask(data=v)) for k, v in data.items()}
    if isinstance(data, list | tuple):
        return [_mask(data=v) for v in data]
    if isinstance(data, str):
        return _mask_text(data)
    return data


def trace_user_id(user_id: str) -> str:
    """user_id as shown in Langfuse. Trace attributes (user_id/metadata) are NOT passed through `mask`, so an
    email-shaped id (AUTH_USER_CLAIM=email) is replaced by a stable hash when PII masking is on."""
    if _mask_pii and _EMAIL_RE.fullmatch(user_id):
        return "u-" + hashlib.sha256(user_id.encode()).hexdigest()[:16]
    return user_id


# --------------------------------------------------------------------------- LangChain bridge
def langchain_callbacks() -> list[Any]:
    """CallbackHandler attached to the graph's RunnableConfig — auto-traces nodes/LLM/tools."""
    if _client is None:
        return []
    from langfuse.langchain import CallbackHandler

    return [CallbackHandler()]


# --------------------------------------------------------------------------- trace / spans
@contextlib.contextmanager
def trace_request(
    *,
    settings: Settings,
    user_id: str,
    session_id: str,
    input: Any,
    metadata: dict[str, Any] | None = None,
    tags: list[str] | None = None,
) -> Iterator[Any]:
    """Root observation + propagates user/session/tags/version to ALL child observations."""
    if _client is None:
        yield None
        return
    from langfuse import propagate_attributes

    with _client.start_as_current_observation(
        name="agent.invoke", as_type="agent", input=input, metadata=metadata
    ) as root:
        with propagate_attributes(
            user_id=trace_user_id(user_id),
            session_id=session_id,
            tags=[settings.agent_name, settings.app_env, *(tags or [])],
            version=settings.agent_version,
            trace_name=f"{settings.agent_name}.invoke",
            metadata={k: str(v) for k, v in (metadata or {}).items()},
        ):
            try:
                yield root
            except BaseException as e:
                root.update(level="ERROR", status_message=f"{type(e).__name__}: {e}")
                raise


class _Step:
    """Span handle: always has .set(...) even when tracing is off."""

    def __init__(self, obs: Any, started: float):
        self._obs = obs
        self._started = started

    def set(
        self,
        *,
        output: Any = None,
        metadata: dict | None = None,
        level: str | None = None,
        status_message: str | None = None,
    ) -> None:
        if self._obs is None:
            return
        meta = {
            "latency_ms": round((time.perf_counter() - self._started) * 1000, 1),
            **(metadata or {}),
        }
        kwargs: dict[str, Any] = {"metadata": meta}
        if output is not None:
            kwargs["output"] = output
        if level:
            kwargs["level"] = level
        if status_message:
            kwargs["status_message"] = status_message
        self._obs.update(**kwargs)


def _langchain_parent() -> Any:
    """Langfuse observation of the currently running LangChain run (node / tool), if any.

    CallbackHandler does not set the node's observation as the OTel "current span" for code inside
    the node, so custom spans must be attached manually to the current run to land correctly in the trace tree.
    """
    from langchain_core.runnables.config import var_child_runnable_config

    cfg = var_child_runnable_config.get()
    manager = cfg.get("callbacks") if cfg else None
    run_id = getattr(manager, "parent_run_id", None)
    if run_id is None:
        return None
    for h in getattr(manager, "handlers", None) or []:
        runs = getattr(h, "_runs", None)
        if runs and run_id in runs:
            return runs[run_id]
    return None


@contextlib.contextmanager
def step(
    name: str, *, input: Any = None, metadata: dict | None = None, as_type: str = "span"
) -> Iterator[_Step]:
    """Child span for NON-LangChain steps (auth, MCP, memory, compression, external APIs...).

    Attaches to the running LangGraph node/tool if any, otherwise to the current span.
    Exceptions inside are marked level=ERROR and re-raised.
    """
    started = time.perf_counter()
    if _client is None:
        yield _Step(None, started)
        return
    parent = _langchain_parent()
    if parent is not None:
        obs = parent.start_observation(name=name, as_type=as_type, input=input, metadata=metadata)
        handle = _Step(obs, started)
        try:
            yield handle
        except BaseException as e:
            handle.set(level="ERROR", status_message=f"{type(e).__name__}: {e}")
            raise
        finally:
            obs.end()
        return
    with _client.start_as_current_observation(
        name=name, as_type=as_type, input=input, metadata=metadata
    ) as obs:
        handle = _Step(obs, started)
        try:
            yield handle
        except BaseException as e:
            handle.set(level="ERROR", status_message=f"{type(e).__name__}: {e}")
            raise


def event(
    name: str,
    *,
    input: Any = None,
    output: Any = None,
    metadata: dict | None = None,
    level: str | None = None,
) -> None:
    """Instant marker (no duration)."""
    if _client is None:
        return
    parent = _langchain_parent()
    if parent is not None:
        parent.start_observation(
            name=name, as_type="event", input=input, output=output, metadata=metadata, level=level
        ).end()
        return
    _client.create_event(name=name, input=input, output=output, metadata=metadata, level=level)


def current_trace_id() -> str | None:
    return _client.get_current_trace_id() if _client is not None else None


def current_trace_url() -> str | None:
    return _client.get_trace_url() if _client is not None else None


def score_trace(name: str, value: float, *, comment: str | None = None) -> None:
    """Attach a score (online evaluation) to the current trace, e.g. self_eval, hitl_approved."""
    trace_id = current_trace_id()
    if _client is None or trace_id is None:
        return
    _client.create_score(
        trace_id=trace_id, name=name, value=value, comment=comment, data_type="NUMERIC"
    )


def record_feedback(*, trace_id: str, value: float, comment: str | None = None) -> bool:
    if _client is None:
        return False
    _client.create_score(
        trace_id=trace_id, name="user_feedback", value=value, comment=comment, data_type="NUMERIC"
    )
    return True
